### ISSUE TITLE
In App Layout, dont force white background in samples

### ISSUE THREAD

**Issue by hyyan** [DwcJava/dwcjava.github.io#15]
BBj define three levels of surfaces which are used to organize the UI hierarchy combined with [bbj-shadows](https://basishub.github.io/basis-next/#/theme-engine/style?id=shadow). Forcing white background ruins the UI hierarchy

https://dwcj.org/docs/components/layouts/app-layout

**Comment by mhawkinsbasis** [comment]
Fixed via:
https://github.com/DwcJava/ControlSamples/commit/d9d88f84f43fb8a412c91015e276134a76fffefc
