### ISSUE TITLE
Cannot load the Drawer docs in Chomre

### ISSUE THREAD

**Issue by hyyan** [DwcJava/dwcjava.github.io#61]
https://dwcj.org/docs/components/drawer

![Screenshot 2023-12-04 at 12 00 03 PM](https://github.com/DwcJava/dwcjava.github.io/assets/4313420/41ccdbc5-ef1f-431c-a21f-b2f7978b8264)

**Comment by MatthewHawkins** [comment]
Loads in Chrome 120.0.6099.224 as of 23-1
