### ISSUE TITLE
Getting started button on home page lead to wrong page

### ISSUE THREAD

**Issue by hyyan** [DwcJava/dwcjava.github.io#7]
The getting started page should link the [getting started page](https://dwcj.org/docs/category/getting-started) or simplified getting start page. See what we do in the [BBjGridExWidget docs](https://bbj-plugins.github.io/BBjGridExWidget/)

**Comment by mhawkinsbasis** [comment]
Created separate issue for the creation of a new Getting Started section for new users - closing this issue as I have redirected the button on the homepage.

Fixed by:
https://github.com/DwcJava/dwcjava.github.io/commit/687b3127271a65d578374cdfeac0b540f37bbd98

**Comment by mhawkinsbasis** [comment]
https://github.com/DwcJava/dwcjava.github.io/issues/19
