### ISSUE TITLE
“Feel free …. “ form in the docs 

### ISSUE THREAD

**Issue by hyyan** [DwcJava/dwcjava.github.io#97]
For documentation sites, it's better to avoid "Feel free to..." as it lacks the precision and clarity needed in instructional content. This phrase can imply optional actions, which might lead to inconsistency in following procedures or understanding concepts. Documentation should aim for unambiguous directives to ensure users have a clear and reliable guide, especially in technical or complex subject matter. Choosing direct and specific language over casual phrases enhances the effectiveness and user-friendliness of the documentation.

**Comment by MatthewHawkins** [comment]
Fixed per commit 79587d9
